# @format

consumes:
  - application/json
info:
  title: Microfest
  contact:
    name: J. Iqbal
    url: https://github.com/LGUG2Z/microfest
    email: jade@beamery.com
  description: Micro Application Manifest Manager
  version: 0.1.0
paths:
  /backup:
    post:
      summary: Backs up the database to a GCS bucket
      operationId: PostBackup
      security:
        - APIKeyHeader: []
      produces:
        - text/plain
      parameters:
        - $ref: '#/parameters/Bucket'
      responses:
        201:
          description: Backup Created
          schema:
            type: string
        401:
          $ref: '#/responses/Unauthorized'
        500:
          $ref: '#/responses/InternalServerError'
  /info:
    get:
      summary: Gets information about the current manifest
      operationId: GetInfo
      security:
        - APIKeyHeader: []
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/Key'
        - $ref: '#/parameters/Host'
      responses:
        200:
          description: OK
          schema:
            description: The requested manifest
            type: object
        404:
          description: Not Found
          schema:
            type: string
        500:
          $ref: '#/responses/InternalServerError'
  /manifest:
    get:
      summary: Gets the latest manifest
      operationId: GetManifest
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/Host'
      responses:
        200:
          description: OK
          schema:
            description: The latest manifest
            type: object
          headers:
            Cache-Control:
              description: Cache-Control
              type: string
        500:
          $ref: '#/responses/InternalServerError'
    put:
      summary: Submits a patch to create a new manifest
      operationId: PutManifest
      security:
        - APIKeyHeader: []
      consumes:
        - application/json
      produces:
        - text/plain
      parameters:
        - $ref: '#/parameters/Host'
        - $ref: '#/parameters/Microfest'
      responses:
        201:
          $ref: '#/responses/ManifestCreated'
        400:
          description: Bad Request Body
        401:
          $ref: '#/responses/Unauthorized'
        500:
          $ref: '#/responses/InternalServerError'
    post:
      summary: Submits a new manifest
      operationId: PostManifest
      security:
        - APIKeyHeader: []
      consumes:
        - application/json
      produces:
        - text/plain
      parameters:
        - $ref: '#/parameters/Host'
        - $ref: '#/parameters/Microfest'
      responses:
        201:
          $ref: '#/responses/ManifestCreated'
        400:
          description: Bad Request Body
        401:
          $ref: '#/responses/Unauthorized'
        500:
          $ref: '#/responses/InternalServerError'
produces:
  - application/json
schemes:
  - http
swagger: "2.0"
securityDefinitions:
  APIKeyHeader:
    type: apiKey
    in: header
    name: X-API-KEY
definitions:
  principal:
    type: string
parameters:
  Bucket:
    in: query
    name: bucket
    type: string
    description: The GCS bucket to back up to
    required: true
  Key:
    in: query
    name: key
    type: string
    description: The manifest key
    required: true
  Host:
    in: query
    name: host
    type: string
    description: The environment hostname
    required: true
  Microfest:
    in: body
    name: microfest
    description: The manifest to submit
    schema:
      type: object
      maxProperties: 3
      required:
        - release
        - manifest
        - updated
      properties:
        release:
          type: string
        manifest:
          type: object
        updated:
          type: array
          items:
            type: string

responses:
  ManifestCreated:
    description: Manifest Created
    schema:
      type: string
  Unauthorized:
    description: Unauthorized
    headers:
      WWW-Authenticate:
        description: Authorization information is missing or invalid
        type: string
  InternalServerError:
    description: Internal Server Error
    schema:
      type: string
