// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetInfoOKCode is the HTTP code returned for type GetInfoOK
const GetInfoOKCode int = 200

/*GetInfoOK OK

swagger:response getInfoOK
*/
type GetInfoOK struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewGetInfoOK creates GetInfoOK with default headers values
func NewGetInfoOK() *GetInfoOK {

	return &GetInfoOK{}
}

// WithPayload adds the payload to the get info o k response
func (o *GetInfoOK) WithPayload(payload interface{}) *GetInfoOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get info o k response
func (o *GetInfoOK) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetInfoOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetInfoNotFoundCode is the HTTP code returned for type GetInfoNotFound
const GetInfoNotFoundCode int = 404

/*GetInfoNotFound Not Found

swagger:response getInfoNotFound
*/
type GetInfoNotFound struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetInfoNotFound creates GetInfoNotFound with default headers values
func NewGetInfoNotFound() *GetInfoNotFound {

	return &GetInfoNotFound{}
}

// WithPayload adds the payload to the get info not found response
func (o *GetInfoNotFound) WithPayload(payload string) *GetInfoNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get info not found response
func (o *GetInfoNotFound) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetInfoNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetInfoInternalServerErrorCode is the HTTP code returned for type GetInfoInternalServerError
const GetInfoInternalServerErrorCode int = 500

/*GetInfoInternalServerError Internal Server Error

swagger:response getInfoInternalServerError
*/
type GetInfoInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetInfoInternalServerError creates GetInfoInternalServerError with default headers values
func NewGetInfoInternalServerError() *GetInfoInternalServerError {

	return &GetInfoInternalServerError{}
}

// WithPayload adds the payload to the get info internal server error response
func (o *GetInfoInternalServerError) WithPayload(payload string) *GetInfoInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get info internal server error response
func (o *GetInfoInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetInfoInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
