// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetHealthcheckOKCode is the HTTP code returned for type GetHealthcheckOK
const GetHealthcheckOKCode int = 200

/*GetHealthcheckOK OK

swagger:response getHealthcheckOK
*/
type GetHealthcheckOK struct {
}

// NewGetHealthcheckOK creates GetHealthcheckOK with default headers values
func NewGetHealthcheckOK() *GetHealthcheckOK {

	return &GetHealthcheckOK{}
}

// WriteResponse to the client
func (o *GetHealthcheckOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
