// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetManifestOKCode is the HTTP code returned for type GetManifestOK
const GetManifestOKCode int = 200

/*GetManifestOK OK

swagger:response getManifestOK
*/
type GetManifestOK struct {
	/*Cache-Control

	 */
	CacheControl string `json:"Cache-Control"`

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewGetManifestOK creates GetManifestOK with default headers values
func NewGetManifestOK() *GetManifestOK {

	return &GetManifestOK{}
}

// WithCacheControl adds the cacheControl to the get manifest o k response
func (o *GetManifestOK) WithCacheControl(cacheControl string) *GetManifestOK {
	o.CacheControl = cacheControl
	return o
}

// SetCacheControl sets the cacheControl to the get manifest o k response
func (o *GetManifestOK) SetCacheControl(cacheControl string) {
	o.CacheControl = cacheControl
}

// WithPayload adds the payload to the get manifest o k response
func (o *GetManifestOK) WithPayload(payload interface{}) *GetManifestOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get manifest o k response
func (o *GetManifestOK) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetManifestOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Cache-Control

	cacheControl := o.CacheControl
	if cacheControl != "" {
		rw.Header().Set("Cache-Control", cacheControl)
	}

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetManifestUnauthorizedCode is the HTTP code returned for type GetManifestUnauthorized
const GetManifestUnauthorizedCode int = 401

/*GetManifestUnauthorized Unauthorized

swagger:response getManifestUnauthorized
*/
type GetManifestUnauthorized struct {
	/*Authorization information is missing or invalid

	 */
	WWWAuthenticate string `json:"WWW-Authenticate"`
}

// NewGetManifestUnauthorized creates GetManifestUnauthorized with default headers values
func NewGetManifestUnauthorized() *GetManifestUnauthorized {

	return &GetManifestUnauthorized{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the get manifest unauthorized response
func (o *GetManifestUnauthorized) WithWWWAuthenticate(wWWAuthenticate string) *GetManifestUnauthorized {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the get manifest unauthorized response
func (o *GetManifestUnauthorized) SetWWWAuthenticate(wWWAuthenticate string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WriteResponse to the client
func (o *GetManifestUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW-Authenticate

	wWWAuthenticate := o.WWWAuthenticate
	if wWWAuthenticate != "" {
		rw.Header().Set("WWW-Authenticate", wWWAuthenticate)
	}

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// GetManifestNotFoundCode is the HTTP code returned for type GetManifestNotFound
const GetManifestNotFoundCode int = 404

/*GetManifestNotFound Not Found

swagger:response getManifestNotFound
*/
type GetManifestNotFound struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetManifestNotFound creates GetManifestNotFound with default headers values
func NewGetManifestNotFound() *GetManifestNotFound {

	return &GetManifestNotFound{}
}

// WithPayload adds the payload to the get manifest not found response
func (o *GetManifestNotFound) WithPayload(payload string) *GetManifestNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get manifest not found response
func (o *GetManifestNotFound) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetManifestNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetManifestInternalServerErrorCode is the HTTP code returned for type GetManifestInternalServerError
const GetManifestInternalServerErrorCode int = 500

/*GetManifestInternalServerError Internal Server Error

swagger:response getManifestInternalServerError
*/
type GetManifestInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetManifestInternalServerError creates GetManifestInternalServerError with default headers values
func NewGetManifestInternalServerError() *GetManifestInternalServerError {

	return &GetManifestInternalServerError{}
}

// WithPayload adds the payload to the get manifest internal server error response
func (o *GetManifestInternalServerError) WithPayload(payload string) *GetManifestInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get manifest internal server error response
func (o *GetManifestInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetManifestInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
