// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetManifestHandlerFunc turns a function with the right signature into a get manifest handler
type GetManifestHandlerFunc func(GetManifestParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetManifestHandlerFunc) Handle(params GetManifestParams) middleware.Responder {
	return fn(params)
}

// GetManifestHandler interface for that can handle valid get manifest params
type GetManifestHandler interface {
	Handle(GetManifestParams) middleware.Responder
}

// NewGetManifest creates a new http.Handler for the get manifest operation
func NewGetManifest(ctx *middleware.Context, handler GetManifestHandler) *GetManifest {
	return &GetManifest{Context: ctx, Handler: handler}
}

/*GetManifest swagger:route GET /manifest getManifest

Gets the latest manifest

*/
type GetManifest struct {
	Context *middleware.Context
	Handler GetManifestHandler
}

func (o *GetManifest) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetManifestParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
