// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetManifestOKCode is the HTTP code returned for type GetManifestOK
const GetManifestOKCode int = 200

/*GetManifestOK OK

swagger:response getManifestOK
*/
type GetManifestOK struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewGetManifestOK creates GetManifestOK with default headers values
func NewGetManifestOK() *GetManifestOK {

	return &GetManifestOK{}
}

// WithPayload adds the payload to the get manifest o k response
func (o *GetManifestOK) WithPayload(payload interface{}) *GetManifestOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get manifest o k response
func (o *GetManifestOK) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetManifestOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetManifestInternalServerErrorCode is the HTTP code returned for type GetManifestInternalServerError
const GetManifestInternalServerErrorCode int = 500

/*GetManifestInternalServerError Internal Server Error

swagger:response getManifestInternalServerError
*/
type GetManifestInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetManifestInternalServerError creates GetManifestInternalServerError with default headers values
func NewGetManifestInternalServerError() *GetManifestInternalServerError {

	return &GetManifestInternalServerError{}
}

// WithPayload adds the payload to the get manifest internal server error response
func (o *GetManifestInternalServerError) WithPayload(payload string) *GetManifestInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get manifest internal server error response
func (o *GetManifestInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetManifestInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
