// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostBackupParams creates a new PostBackupParams object
// no default values defined in spec.
func NewPostBackupParams() PostBackupParams {

	return PostBackupParams{}
}

// PostBackupParams contains all the bound params for the post backup operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostBackup
type PostBackupParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*GCS bucket name
	  Required: true
	  In: query
	*/
	Bucket string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostBackupParams() beforehand.
func (o *PostBackupParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qBucket, qhkBucket, _ := qs.GetOK("bucket")
	if err := o.bindBucket(qBucket, qhkBucket, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindBucket binds and validates parameter Bucket from query.
func (o *PostBackupParams) bindBucket(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("bucket", "query")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false
	if err := validate.RequiredString("bucket", "query", raw); err != nil {
		return err
	}

	o.Bucket = raw

	return nil
}
