// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/LGUG2Z/microfest/models"
)

// PostBackupHandlerFunc turns a function with the right signature into a post backup handler
type PostBackupHandlerFunc func(PostBackupParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn PostBackupHandlerFunc) Handle(params PostBackupParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// PostBackupHandler interface for that can handle valid post backup params
type PostBackupHandler interface {
	Handle(PostBackupParams, *models.Principal) middleware.Responder
}

// NewPostBackup creates a new http.Handler for the post backup operation
func NewPostBackup(ctx *middleware.Context, handler PostBackupHandler) *PostBackup {
	return &PostBackup{Context: ctx, Handler: handler}
}

/*PostBackup swagger:route POST /backup postBackup

Backs up the database to a GCS bucket

*/
type PostBackup struct {
	Context *middleware.Context
	Handler PostBackupHandler
}

func (o *PostBackup) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostBackupParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
