// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostBackupCreatedCode is the HTTP code returned for type PostBackupCreated
const PostBackupCreatedCode int = 201

/*PostBackupCreated Backup Created

swagger:response postBackupCreated
*/
type PostBackupCreated struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewPostBackupCreated creates PostBackupCreated with default headers values
func NewPostBackupCreated() *PostBackupCreated {

	return &PostBackupCreated{}
}

// WithPayload adds the payload to the post backup created response
func (o *PostBackupCreated) WithPayload(payload string) *PostBackupCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post backup created response
func (o *PostBackupCreated) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostBackupCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// PostBackupUnauthorizedCode is the HTTP code returned for type PostBackupUnauthorized
const PostBackupUnauthorizedCode int = 401

/*PostBackupUnauthorized Unauthorized

swagger:response postBackupUnauthorized
*/
type PostBackupUnauthorized struct {
	/*Authorization information is missing or invalid

	 */
	WWWAuthenticate string `json:"WWW-Authenticate"`
}

// NewPostBackupUnauthorized creates PostBackupUnauthorized with default headers values
func NewPostBackupUnauthorized() *PostBackupUnauthorized {

	return &PostBackupUnauthorized{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the post backup unauthorized response
func (o *PostBackupUnauthorized) WithWWWAuthenticate(wWWAuthenticate string) *PostBackupUnauthorized {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the post backup unauthorized response
func (o *PostBackupUnauthorized) SetWWWAuthenticate(wWWAuthenticate string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WriteResponse to the client
func (o *PostBackupUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW-Authenticate

	wWWAuthenticate := o.WWWAuthenticate
	if wWWAuthenticate != "" {
		rw.Header().Set("WWW-Authenticate", wWWAuthenticate)
	}

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// PostBackupInternalServerErrorCode is the HTTP code returned for type PostBackupInternalServerError
const PostBackupInternalServerErrorCode int = 500

/*PostBackupInternalServerError Internal Server Error

swagger:response postBackupInternalServerError
*/
type PostBackupInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewPostBackupInternalServerError creates PostBackupInternalServerError with default headers values
func NewPostBackupInternalServerError() *PostBackupInternalServerError {

	return &PostBackupInternalServerError{}
}

// WithPayload adds the payload to the post backup internal server error response
func (o *PostBackupInternalServerError) WithPayload(payload string) *PostBackupInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post backup internal server error response
func (o *PostBackupInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostBackupInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
