// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Microfest
Micro Application Manifest and Configuration Manager


    Schemes:
      http
    Host: localhost
    BasePath: /
    Version: 0.0.1
    Contact: J. Iqbal<jade@beamery.com> https://github.com/LGUG2Z/microfest

    Consumes:
    - application/json

    Produces:
    - application/json
    - text/plain

swagger:meta
*/
package restapi
